### ISSUE TITLE
Mac m1无法从全屏启动

### ISSUE THREAD

**Issue by zxqlxy** [imengyu/Ballance#11]
<img width="983" alt="image" src="https://github.com/imengyu/Ballance/assets/31945884/2049bfa2-b0da-43be-a13f-af5dd809da38">

**Comment by imengyu** [comment]
感谢您提出问题，修复会在下个版本发布

**Comment by pkgamma** [comment]
I think this issue happens to me when I start the game in one resolution, end the game, then switch to a display with a lower resolution, and there seems to be no way to bypass this except to switch back to the original, higher resolution display.

**Comment by aaasoft** [comment]
看起来imengyu已经修复此问题了，所以关闭此issue。
