### ISSUE TITLE
No text in menu and in tutorial

### ISSUE THREAD

**Issue by blwckcore** [imengyu/Ballance#12]
![Снимок экрана (37)](https://github.com/imengyu/Ballance/assets/107321994/5629cbf8-5f73-4199-bc68-7cf3bf274209)
![Снимок экрана (38)](https://github.com/imengyu/Ballance/assets/107321994/c2a45b0a-a90a-4d50-ac74-f3bf55cae9f1)
By the way, same happens to me on mobile. On both I have russian language set.

**Comment by aaasoft** [comment]
Hi,the project just have Chinese and English language now.so other language can't display correct.

**Comment by aaasoft** [comment]
Now you can try version 1.0.6,add language fall back feature.now will fall back to English when russian language resource not found.

**Comment by blwckcore** [comment]
yep, now everything is fine, thanks
