### ISSUE TITLE
Linux版本运行失败

### ISSUE THREAD

**Issue by jerry4718** [imengyu/Ballance#16]
![image](https://github.com/imengyu/Ballance/assets/17174523/09b20729-dee9-471f-a688-2be12221a15f)

**Comment by aaasoft** [comment]
看错误信息是提示没有找到物理引擎的文件导致的。你那边什么发行版本？CPU架构是什么呢？最好是把neofetch结果发上来看看。

**Comment by aaasoft** [comment]
我在虚拟机里面安装了Deepin 20.9系统。找到问题了。是Deepin 20.9的glibc版本太低了，是2.28版本。物理引擎so文件需要gblic 2.29及以上的版本才能正常加载。建议更新glibc到2.29以上版本，或者安装Deepin 23。

![image](https://github.com/imengyu/Ballance/assets/1552027/bab5fcda-caf3-4161-a05d-8997fb339e95)

**Comment by jerry4718** [comment]
原来又是glibc的锅
