### ISSUE TITLE
Android版本增加蓝牙手柄支持

### ISSUE THREAD

**Issue by aaasoft** [imengyu/Ballance#18]
现在电视都是Android系统，安装在电视上时，无法通过连接电视的蓝牙手柄进行操作。建议加上此功能，同时检测到手柄或者键盘操作时，隐藏屏幕上的操作按钮。

操作建议：
左摇杆和十字键：操作球运行
LB肩键：左转视角
RB肓键：右转视角
LT/RT扳机键：俯瞰视角

**Comment by aaasoft** [comment]
我提交了一个Pull Reuest，加上了手柄操作支持功能。

**Comment by imengyu** [comment]
非常感谢您，只是这个项目我已经不打算再维护或者发布新版了。您可以自己发布版本

**Comment by aaasoft** [comment]
好的，Pull Request #19 这次只增加了XBox手柄的支持，普通手柄还有支持的。后面再增加上普通手柄的支持。

**Comment by aaasoft** [comment]
> 感谢两位呜呜呜 希望这个项目能继续发展下去！

哈哈，我也只是把手柄支持功能加好了。游戏的其他部分也不懂。希望有其他懂游戏的人也能参与进来。
