### ISSUE TITLE
Windows 11 下无法启动游戏

### ISSUE THREAD

**Issue by david4958606** [imengyu/Ballance#2]
最新发行版（0.9.5）

报错如下：

![image](https://user-images.githubusercontent.com/16517322/167343714-7ad12835-f781-4129-8c2c-1b504368a5e6.png)

```text
Failed to load PlayerSettings (internal index #0).
Most likely data file is corrupted, or built with mismatching
editor and platform support versions.
```

Windows 11 build 22000.652

**Comment by imengyu** [comment]
修复好啦。昨天打包的时候打包错了 /(ㄒoㄒ)/~~ 可以重新下载这个 https://github.com/imengyu/Ballance/releases/download/v0.9.5/0.9.5-windows-x86.zip
