### ISSUE TITLE
macOS 12.3 无法启动游戏

### ISSUE THREAD

**Issue by jjaychen1e** [imengyu/Ballance#3]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/31304335/167531114-8c6a959e-2b98-4f8d-8568-82ac75610497.png">
<img width="918" alt="image" src="https://user-images.githubusercontent.com/31304335/167531139-f9094d5d-41bd-486d-afa2-8665163a70f8.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/31304335/167531153-4ca0c8aa-c3db-4f59-bb9d-993d0d3b0c62.png">

**Comment by imengyu** [comment]
抱歉，暂时不支持M1，两个原生库slua，物理引擎，目前只有intel 64版本的。我暂时也没有搭载M1的苹果电脑，测试不了。最近很忙，没有太多时间完善了。如果感兴趣的话可以自己编译下slua和物理引擎，替换掉包内的PlugIns

**Comment by imengyu** [comment]
1.0.2 现在已经支持 Mac
