### ISSUE TITLE
请问“菜单 -> 设置 -> 控制 -> 反向控制”这一选项的作用是否与原作“Options -> Controls -> Invert rotation”选项一致？

### ISSUE THREAD

**Issue by nukemiko** [imengyu/Ballance#6]
原作中的这个设置叫 Invert Rotation，开启后只会反转按键时视角的旋转方向；重制版中此设置会直接反转四个方向键所控制的移动方向（按↑/↓键球往屏幕下方/上方移动，按←/→键球往屏幕右边/左边移动）。

请问这两个选项是否是同一个选项呢？

**Comment by imengyu** [comment]
非常感谢您提出问题！是我写错了，从来没有用过这个选项，我以为是反向控制（看到中文版的翻译望文生义了），我修改下

**Comment by imengyu** [comment]
v0.9.8 已经修复问题
