### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by yunjuyihao** [imengyu/Ballance#7]
1换视角的原理似乎不太对，原版是同时摁下触发，而这个是同时抬起触发（0.9.3）而且成功率感人
2风扇的判定有点小？
3当fps过大时，分数球会鬼畜

**Comment by imengyu** [comment]
非常感谢你的建议，0.9.9 已经修改啦

**Comment by imengyu** [comment]
关于风扇判定，碰撞箱与原版一致，是大小为 2x16x2 的立方体。
