### ISSUE TITLE
Request for adding English readme and linux version

### ISSUE THREAD

**Issue by chiefdinkan** [imengyu/Ballance#9]
大家好，我一直关注着这个项目，这个游戏是我的童年回忆之一。这个开源重新实现项目是我最喜欢的项目之一，因为它让我可以重新体验这个游戏。在最近的git提交之前，英文版的README页面非常有用，能够帮助我安装游戏。因此，我请求重新添加已删除的 `readme.en.md` 页面，该页面包含了英文翻译。

此外，我希望在发布页面中能够提供Linux原生版本的构建，因为许多用户（包括我自己）使用Linux，并且会受益于此。

The above message appears to have been translated using Google Translate, so I apologize if it doesn't make sense.

---

Hi, I have been following this project for a while and this is one of my nostalgic childhood games that I have played. This open source reimplementation is one of my favorite projects, as it allows me to re-experience the game. Before the recent git commit, the README page in English was greatly helpful for installing the game. Therefore, I request to re-add the deleted `readme.en.md` page, which contained the English translation.

Additionally, I would appreciate a Linux native release build in the Releases page, as many users (including myself) use Linux and would appreciate this.

**Comment by imengyu** [comment]
Thank you for your following 😀. I will add Linux build later

**Comment by chiefdinkan** [comment]
Thanks!. Downloaded it and it works smoothly under Wayland!
